version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3g
    steps:
      - add_ssh_keys:
          fingerprints:
            - "MD5:04:99:22:0d:36:e0:2a:77:8b:7d:87:64:ea:2e:87:4e"
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - run: mvn jacoco:report
      - store_artifacts:
          path:  target
      - codecov/upload:
          file: './target/site/jacoco/jacoco.xml'
          token: dc9b1464-bf30-4695-9502-99160daa6ac5

workflows:
  version: 2.1
  workflow:
    jobs:
    - build

orbs:
  codecov: codecov/codecov@1.0.2
 