version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3g
    steps:
      - add_ssh_keys:
          fingerprints:
            - "MD5:04:99:22:0d:36:e0:2a:77:8b:7d:87:64:ea:2e:87:4e"
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: mvn clean package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      # run tests!
      - run: mvn integration-test
