DROP TABLE T_CARD_GROUP CASCADE;
DROP TABLE T_USER_GROUP CASCADE;
DROP TABLE T_CARD CASCADE;
DROP TABLE T_GROUP CASCADE;
DROP TABLE T_USER CASCADE;
DROP TABLE T_COMPANY CASCADE;
DROP TABLE databasechangelog;
DROP TABLE databasechangeloglock;